#!/bin/bash
# setup-lab.sh - Rebuild DevOps lab structure

echo "🔧 Setting up DevOps lab..."

# Create directories
mkdir -p docs scripts logs projects/hello-app

# Create sample files
cat > docs/README.md <<'INNER'
# DevOps Lab
Auto-generated by setup-lab.sh
INNER

cat > logs/access.log <<'INNER'
192.168.1.10 - - [27/Oct/2025:10:00:00 +0500] "GET /api/test HTTP/1.1" 200 100 "Mozilla/5.0"
INNER

echo "✅ Lab setup complete!"
